### REQUERIMIENTOS

1. Generar un par de arrays ficticios con numpy.

In [33]:
import numpy as np

cantidad = 20
array1 = np.linspace(1, 50, cantidad).astype(int)
array2 = np.linspace(50, 150, cantidad).astype(int)
display(array1,array2)

array([ 1,  3,  6,  8, 11, 13, 16, 19, 21, 24, 26, 29, 31, 34, 37, 39, 42,
       44, 47, 50])

array([ 50,  55,  60,  65,  71,  76,  81,  86,  92,  97, 102, 107, 113,
       118, 123, 128, 134, 139, 144, 150])

2. Ejecuta un loop que devuelva si el número en el primer array es par o impar.

In [34]:
for num in array1:
    if num%2 == 0:
        print(f'> El numero {num} es par')
    else: print(f'> El numero {num} es impar')

> El numero 1 es impar
> El numero 3 es impar
> El numero 6 es par
> El numero 8 es par
> El numero 11 es impar
> El numero 13 es impar
> El numero 16 es par
> El numero 19 es impar
> El numero 21 es impar
> El numero 24 es par
> El numero 26 es par
> El numero 29 es impar
> El numero 31 es impar
> El numero 34 es par
> El numero 37 es impar
> El numero 39 es impar
> El numero 42 es par
> El numero 44 es par
> El numero 47 es impar
> El numero 50 es par


3. Genere un loop con el segundo array que cuente las siguientes condiciones:
* Si el número es divisible por 2 o 3.
* Si el número es divisible por 2 y 3.
* Si el número es divisible por 3 pero no por 2.
* si el número no es divisible por 2 ni 3.


In [38]:
display(array2)
i,j,k,n = 0,0,0,0

for num in array2:
    if num%2 == 0 or num%3 == 0:
        i+=1
    if num%2 == 0 and num%3 == 0:
        j+=1
    if num%3 == 0 and num%2 != 0:
        k+=1
    if num%2 != 0 and num%3 !=0:
        n+=1
        
print(f'Numeros que son divisibles por 2 o 3: {i}')
print(f'Numeros que son divisibles por 2 y 3: {j}')
print(f'Numeros que son divisibles por 3 pero no por 2: {k}')
print(f'Numeros que son divisibles por 2 ni 3: {n}')

array([ 50,  55,  60,  65,  71,  76,  81,  86,  92,  97, 102, 107, 113,
       118, 123, 128, 134, 139, 144, 150])

Numeros que son divisibles por 2 o 3: 13
Numeros que son divisibles por 2 y 3: 4
Numeros que son divisibles por 3 pero no por 2: 2
Numeros que son divisibles por 2 ni 3: 7


4. Corrección de errores: Revisa el siguiente código y encuentra los errores a corregir.

In [ ]:
for i in range(100):
    print(I**2)

El error se produce ya que **I** no esta definido, solo **i** esta definido

5. Utilizando la misma base flights.csv debes hacer un loop y clasificar los meses con una cantidad de pasajeros menor a la media. Para ello:
* Genera un nuevo objeto que represente la media de passengers.
* Genera una columna en la base de datos que se llame underperforming y asígnele 0.
* Ejecuta un loop que recorra cada observación de passengers, donde si la observación es menor a la media de passengers se le asigne a underperforming un 1.
* Asignar unos en la columna underperforming ya creada, para ello utilice la función at de pandas.

In [59]:
import pandas as pd

#Guardamos el archivo flights
df = pd.read_csv('flights.csv')

#Obtenemos la media de los pasajeros
mean = df['passengers'].mean()

#Asignamos la nueva columna llamada underperforming y le asignamos 0
df['underperforming'] = 0

#Recorremos df con un loop para asignar un 1 a la columna underperforming segun criterio
for index, value in df['passengers'].items():
    if value < mean :
        df.at[index,'underperforming'] = 1

df
#Mejor forma
#df['underperforming'] = np.where(df['passengers']<mean, 1, 0)

year      month  passengers  underperforming
0    1949    January         112                1
1    1949   February         118                1
2    1949      March         132                1
3    1949      April         129                1
4    1949        May         121                1
..    ...        ...         ...              ...
139  1960     August         606                0
140  1960  September         508                0
141  1960    October         461                0
142  1960   November         390                0
143  1960   December         432                0

[144 rows x 4 columns]

6. Por último, haz un loop que clasifique los meses donde la cantidad de pasajeros se escapa de la tendencia. Para ello:
* Genera dos objetos que guarden la media general y la desviación estándar general de passengers.
* Genera una nueva columna en la tabla de datos que se llame outlier y asígnale 0.
* Ejecuta un loop que recorra cada observación de passengers, donde si la observación se escapa de la tendencia sea 1, de lo contrario 0.
* Para clasificar los casos que se escapen la tendencia, la observación debe satisfacer una de las siguientes condiciones:
  * La observación debe ser menor a la media menos la desviación estándar, o
  - La observación debe ser mayor a la media más la desviación estándar.
  * ¿Cuántas observaciones se pueden clasificar como casos extremos?

In [77]:
#Calculamos la media y desviacion estandar de la columna 'passengers'
media = df['passengers'].mean()
dev = df['passengers'].std()

#Creamos la nueva columna outlier:
df['outlier'] = 0

#Generamos los limites tolerables de la distribucion
limit_up = media + dev
limit_down = media - dev

#Generamos el loop para crear la clasificacion si se escapa o no de la tendencia
for index, value in df['passengers'].items():
    if value > limit_up or value < limit_down :
    #if limit_down <= value <= limit_up :
        df.at[index,'outlier'] = 1

df

year      month  passengers  underperforming  outlier
0    1949    January         112                1        1
1    1949   February         118                1        1
2    1949      March         132                1        1
3    1949      April         129                1        1
4    1949        May         121                1        1
..    ...        ...         ...              ...      ...
139  1960     August         606                0        1
140  1960  September         508                0        1
141  1960    October         461                0        1
142  1960   November         390                0        0
143  1960   December         432                0        1

[144 rows x 5 columns]